services:

  postgres:
    image: postgres:15
    container_name: webcrawl-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webcrawl
    ports:
      - "5433:5432"
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webcrawl-net

  redis:
    image: redis:7
    container_name: webcrawl-redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webcrawl-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: webcrawl-rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webcrawl-net

  minio:
    image: minio/minio
    container_name: webcrawl-minio
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ${UPLOAD_DIR}:/data
      - ./minio/entrypoint.sh:/entrypoint.sh
      
    entrypoint: ["/bin/sh","/entrypoint.sh"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - webcrawl-net


  auth-service:
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
    container_name: webcrawl-auth
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "5000:5000"
    networks:
      - webcrawl-net


  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    container_name: webcrawl-gateway
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      auth-service:
        condition: service_started
    ports:
      - "4000:4000"
    networks:
      - webcrawl-net


  crawl-manager:
    build:
      context: .
      dockerfile: apps/crawl-manager/Dockerfile
    container_name: webcrawl-manager
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3002:3002"
    networks:
      - webcrawl-net


  crawl-worker:
    build:
      context: .
      dockerfile: apps/crawl-worker/Dockerfile
    container_name: webcrawl-worker
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - webcrawl-net


  analysis-service:
    build:
      context: .
      dockerfile: apps/analysis-service/Dockerfile
    container_name: webcrawl-analysis
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - webcrawl-net


  reporting-service:
    build:
      context: .
      dockerfile: apps/reporting-service/Dockerfile
    container_name: webcrawl-reporting
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4004:4004"
    networks:
      - webcrawl-net


  report-generator:
    build:
      context: .
      dockerfile: apps/report-generator/Dockerfile
    container_name: webcrawl-report-generator
    restart: always
    env_file:
      - .env
    environment:
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - webcrawl-net


  web-app:
    build:
      context: .
      dockerfile: apps/web-app/Dockerfile
    container_name: webcrawl-web
    restart: always
    depends_on:
      api-gateway:
        condition: service_started
    ports:
      - "80:80"
    networks:
      - webcrawl-net


networks:
  webcrawl-net:
    driver: bridge